spring.application.name=codelobster

# JWT settings (change secret per environment)
app.security.jwt.secret=ShgIyc5K3Q0oYEPrkMOhj5vkdeYsCS55Gtug0DAmMhF
app.security.jwt.issuer=lobstercode-backend
app.security.jwt.access-token-expiration-seconds=900
app.security.jwt.refresh-token-expiration-seconds=2592000

# Ranking policy
app.ranking.min-solved-for-rank=5
app.ranking.min-contests-for-rank=1
app.ranking.default-global-rank=2147483647
